### ISSUE TITLE
X and Y

### ISSUE THREAD

**Issue by sharmzy** [VioSynthax/Klippventurer-Pi#7]
X and Y have a 17 tooth pulley 2mm pitch, why 33.33, it will throw dimensions of parts off, update that to 34,  tooth count x pitch as per manual ;) also Z probably will work better at 6.4 its not metric but a 1/4" 4 start so that's 0.063 inch/rev, converted 1.6mm X 4 starts, print some parts that require dimensional accuracy. working on a FF CANBUS 4 filament ERCF, love to see other adv enthusiasts I will be sure to watch your progress, great work.

**Comment by VioSynthax** [comment]
> X and Y have a 17 tooth pulley 2mm pitch, why 33.33, it will throw dimensions of parts off, update that to 34, tooth count x pitch as per manual ;) also Z probably will work better at 6.4 its not metric but a 1/4" 4 start so that's 0.063 inch/rev, converted 1.6mm X 4 starts, print some parts that require dimensional accuracy. working on a FF CANBUS 4 filament ERCF, love to see other adv enthusiasts I will be sure to watch your progress, great work.

Hey, thanks for opening an issue on this one. I think when I set that up I just considered it "good enough" based on the test prints I was doing, as I was having some difficulties trying to figure out why the "right" numbers were very dimensionally wrong. (I might have miscounted the number of teeth, oopsie) I think what I ultimately did was multiply my numbers by the scaling factor I measured from my test prints. In other words, the "wrong" way, but what can I say, I came from Marlin 😆

I really appreciate you giving me proper numbers. I'd definitely be interested in seeing your project, it sounds very interesting!
